insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (1, 1, 'http://hugedomains.com', 22, 'Open-source content-based customer loyalty', '08-06-2023', 78);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (2, 1, 'http://sina.com.cn', 13, 'Grass-roots local synergy', '03-08-2022', 62);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (3, 1, 'https://nationalgeographic.com', 29, 'Multi-channelled systemic ability', '06-09-2022', 74);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (4, 2, 'http://mtv.com', 16, 'Optimized directional firmware', '23-09-2022', 4);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (5, 2, 'http://nbcnews.com', 30, 'Streamlined empowering access', '13-02-2023', 1);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (6, 3, 'https://seesaa.net', 28, 'Vision-oriented bi-directional knowledge user', '25-04-2023', 10);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (7, 3, 'http://chronoengine.com', 16, 'Seamless leading edge moderator', '31-05-2023', 97);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (8, 3, 'https://photobucket.com', 24, 'Business-focused grid-enabled encoding', '03-10-2022', 19);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (9, 1, 'https://java.com', 5, 'Right-sized needs-based superstructure', '05-03-2023', 64);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (10, 2, 'https://latimes.com', 25, 'Right-sized system-worthy capacity', '30-06-2023', 4);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (11, 1, 'https://myspace.com', 15, 'Customer-focused executive open system', '30-06-2023', 3);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (12, 3, 'http://live.com', 21, 'Right-sized radical internet solution', '01-11-2022', 91);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (13, 1, 'https://w3.org', 29, 'User-friendly coherent groupware', '20-12-2022', 91);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (14, 3, 'https://house.gov', 17, 'Fully-configurable static knowledge user', '29-06-2023', 27);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (15, 3, 'http://gmpg.org', 10, 'Programmable responsive internet solution', '28-06-2023', 61);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (16, 3, 'https://illinois.edu', 4, 'Focused asynchronous workforce', '10-01-2023', 15);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (17, 1, 'http://msn.com', 17, 'Phased optimal instruction set', '26-08-2022', 5);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (18, 1, 'http://bbc.co.uk', 6, 'Reverse-engineered incremental interface', '16-06-2023', 83);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (19, 2, 'https://go.com', 9, 'Synergized foreground utilisation', '12-05-2023', 93);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (20, 3, 'http://mit.edu', 30, 'Managed leading edge hub', '17-05-2023', 51);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (21, 1, 'https://yahoo.co.jp', 11, 'Integrated national instruction set', '21-04-2023', 85);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (22, 1, 'https://nature.com', 15, 'Multi-tiered asymmetric info-mediaries', '06-02-2023', 23);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (23, 3, 'http://vinaora.com', 16, 'Fundamental systematic website', '12-05-2023', 67);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (24, 1, 'https://paginegialle.it', 23, 'Monitored next generation productivity', '05-02-2023', 67);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (25, 1, 'http://tinypic.com', 27, 'Sharable attitude-oriented internet solution', '01-10-2022', 47);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (26, 2, 'https://icq.com', 18, 'Secured asynchronous Graphic Interface', '01-05-2023', 98);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (27, 3, 'http://pcworld.com', 20, 'Streamlined 4th generation leverage', '11-12-2022', 63);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (28, 1, 'http://de.vu', 26, 'Focused reciprocal protocol', '13-06-2023', 4);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (29, 1, 'http://newyorker.com', 9, 'Ameliorated global portal', '05-05-2023', 82);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (30, 1, 'http://about.me', 11, 'Stand-alone hybrid open architecture', '21-08-2022', 79);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (31, 2, 'https://devhub.com', 14, 'Ergonomic attitude-oriented superstructure', '29-08-2022', 34);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (32, 2, 'http://barnesandnoble.com', 12, 'Quality-focused solution-oriented synergy', '11-01-2023', 40);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (33, 1, 'https://ox.ac.uk', 12, 'Managed foreground project', '01-05-2023', 80);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (34, 1, 'http://friendfeed.com', 29, 'Multi-lateral methodical secured line', '28-05-2023', 75);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (35, 1, 'http://adobe.com', 29, 'Enhanced mission-critical toolset', '23-09-2022', 35);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (36, 3, 'http://whitehouse.gov', 28, 'Compatible 4th generation info-mediaries', '06-09-2022', 68);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (37, 3, 'https://xrea.com', 5, 'Synergistic full-range budgetary management', '14-12-2022', 19);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (38, 1, 'http://yandex.ru', 6, 'Quality-focused maximized frame', '14-07-2023', 55);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (39, 1, 'http://arizona.edu', 25, 'Object-based clear-thinking leverage', '12-01-2023', 39);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (40, 1, 'https://wix.com', 18, 'Automated eco-centric function', '31-10-2022', 77);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (41, 2, 'http://clickbank.net', 18, 'Expanded user-facing matrices', '26-11-2022', 49);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (42, 3, 'https://fda.gov', 10, 'Expanded national moderator', '16-07-2023', 48);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (43, 2, 'http://mapquest.com', 19, 'Mandatory demand-driven customer loyalty', '30-06-2023', 56);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (44, 2, 'http://usa.gov', 6, 'Devolved neutral secured line', '19-03-2023', 7);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (45, 3, 'http://altervista.org', 30, 'Multi-layered motivating installation', '29-05-2023', 94);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (46, 3, 'http://nih.gov', 16, 'Team-oriented national process improvement', '04-06-2023', 54);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (47, 2, 'http://netlog.com', 20, 'Reactive next generation archive', '15-09-2022', 34);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (48, 3, 'http://sun.com', 29, 'Visionary homogeneous time-frame', '05-08-2022', 10);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (49, 3, 'https://myspace.com', 6, 'Compatible encompassing internet solution', '06-12-2022', 53);
insert into media (id, media_type_id, url, owner_id, description, upload_at, _size) values (50, 3, 'http://creativecommons.org', 13, 'Inverse heuristic analyzer', '29-09-2022', 84);
