insert into products (product_name, manufacturer_id, category_id) values ('in', 57, 5);
insert into products (product_name, manufacturer_id, category_id) values ('venenatis turpis', 37, 8);
insert into products (product_name, manufacturer_id, category_id) values ('iaculis', 4, 6);
insert into products (product_name, manufacturer_id, category_id) values ('justo', 36, 5);
insert into products (product_name, manufacturer_id, category_id) values ('sapien cum', 16, 5);
insert into products (product_name, manufacturer_id, category_id) values ('semper porta', 10, 9);
insert into products (product_name, manufacturer_id, category_id) values ('nulla tempus', 5, 4);
insert into products (product_name, manufacturer_id, category_id) values ('eget', 66, 8);
insert into products (product_name, manufacturer_id, category_id) values ('ipsum primis', 1, 2);
insert into products (product_name, manufacturer_id, category_id) values ('mauris enim', 47, 2);
insert into products (product_name, manufacturer_id, category_id) values ('nec', 34, 9);
insert into products (product_name, manufacturer_id, category_id) values ('nulla', 70, 10);
insert into products (product_name, manufacturer_id, category_id) values ('ac consequat', 12, 8);
insert into products (product_name, manufacturer_id, category_id) values ('lectus vestibulum', 5, 4);
insert into products (product_name, manufacturer_id, category_id) values ('dolor sit', 69, 6);
insert into products (product_name, manufacturer_id, category_id) values ('posuere', 30, 4);
insert into products (product_name, manufacturer_id, category_id) values ('lorem', 28, 10);
insert into products (product_name, manufacturer_id, category_id) values ('posuere metus', 50, 2);
insert into products (product_name, manufacturer_id, category_id) values ('sit', 95, 9);
insert into products (product_name, manufacturer_id, category_id) values ('felis', 41, 1);
insert into products (product_name, manufacturer_id, category_id) values ('duis', 100, 2);
insert into products (product_name, manufacturer_id, category_id) values ('pede justo', 80, 8);
insert into products (product_name, manufacturer_id, category_id) values ('vedl', 56, 6);
insert into products (product_name, manufacturer_id, category_id) values ('vel', 71, 6);
insert into products (product_name, manufacturer_id, category_id) values ('iaculis congue', 59, 2);
insert into products (product_name, manufacturer_id, category_id) values ('augue quam', 62, 1);
insert into products (product_name, manufacturer_id, category_id) values ('bibendum imperdiet', 95, 8);
insert into products (product_name, manufacturer_id, category_id) values ('tortor id', 59, 3);
insert into products (product_name, manufacturer_id, category_id) values ('lacus', 8, 3);
insert into products (product_name, manufacturer_id, category_id) values ('tempus', 49, 6);
insert into products (product_name, manufacturer_id, category_id) values ('aliquam non', 52, 7);
insert into products (product_name, manufacturer_id, category_id) values ('mattis', 96, 3);
insert into products (product_name, manufacturer_id, category_id) values ('nulla suscipit', 9, 3);
insert into products (product_name, manufacturer_id, category_id) values ('augue luctus', 27, 2);
insert into products (product_name, manufacturer_id, category_id) values ('metus', 2, 8);
insert into products (product_name, manufacturer_id, category_id) values ('vitae', 6, 10);
insert into products (product_name, manufacturer_id, category_id) values ('praesent id', 44, 1);
insert into products (product_name, manufacturer_id, category_id) values ('amet diam', 34, 10);
insert into products (product_name, manufacturer_id, category_id) values ('in eleifend', 95, 7);
insert into products (product_name, manufacturer_id, category_id) values ('erat', 16, 9);
insert into products (product_name, manufacturer_id, category_id) values ('a feugiat', 50, 5);
insert into products (product_name, manufacturer_id, category_id) values ('ipsum', 65, 10);
insert into products (product_name, manufacturer_id, category_id) values ('consequat nulla', 95, 8);
insert into products (product_name, manufacturer_id, category_id) values ('consequat in', 10, 4);
insert into products (product_name, manufacturer_id, category_id) values ('volutpat', 36, 2);
insert into products (product_name, manufacturer_id, category_id) values ('integer aliquet', 46, 5);
insert into products (product_name, manufacturer_id, category_id) values ('lectuss vestibulum', 50, 7);
insert into products (product_name, manufacturer_id, category_id) values ('tellus semper', 1, 3);
insert into products (product_name, manufacturer_id, category_id) values ('egest', 2, 4);
insert into products (product_name, manufacturer_id, category_id) values ('nissl', 17, 4);
insert into products (product_name, manufacturer_id, category_id) values ('nissi at', 81, 5);
insert into products (product_name, manufacturer_id, category_id) values ('quasm', 73, 2);
insert into products (product_name, manufacturer_id, category_id) values ('aliquam lacus', 60, 6);
insert into products (product_name, manufacturer_id, category_id) values ('diam', 24, 4);
insert into products (product_name, manufacturer_id, category_id) values ('pede', 61, 1);
insert into products (product_name, manufacturer_id, category_id) values ('condimentum id', 85, 1);
insert into products (product_name, manufacturer_id, category_id) values ('lorsem', 55, 1);
insert into products (product_name, manufacturer_id, category_id) values ('asc nulla', 52, 8);
insert into products (product_name, manufacturer_id, category_id) values ('msetus', 94, 10);
insert into products (product_name, manufacturer_id, category_id) values ('cusbilia', 69, 10);
insert into products (product_name, manufacturer_id, category_id) values ('nsascetur ridiculus', 27, 10);
insert into products (product_name, manufacturer_id, category_id) values ('ssit amet', 15, 5);
insert into products (product_name, manufacturer_id, category_id) values ('maecenas tincidunt', 47, 10);
insert into products (product_name, manufacturer_id, category_id) values ('viverra pede', 70, 10);
insert into products (product_name, manufacturer_id, category_id) values ('sapien a', 11, 9);
insert into products (product_name, manufacturer_id, category_id) values ('pulvinar', 36, 7);
insert into products (product_name, manufacturer_id, category_id) values ('convallis', 27, 10);
insert into products (product_name, manufacturer_id, category_id) values ('accumsan', 33, 5);
insert into products (product_name, manufacturer_id, category_id) values ('duiss', 67, 2);
insert into products (product_name, manufacturer_id, category_id) values ('et', 95, 10);
insert into products (product_name, manufacturer_id, category_id) values ('amet', 75, 3);
insert into products (product_name, manufacturer_id, category_id) values ('semper est', 35, 5);
insert into products (product_name, manufacturer_id, category_id) values ('lectus', 92, 1);
insert into products (product_name, manufacturer_id, category_id) values ('primis', 74, 1);
insert into products (product_name, manufacturer_id, category_id) values ('lobortis ligula', 94, 7);
insert into products (product_name, manufacturer_id, category_id) values ('at diam', 27, 3);
insert into products (product_name, manufacturer_id, category_id) values ('dui nec', 17, 7);
insert into products (product_name, manufacturer_id, category_id) values ('praesent', 75, 6);
insert into products (product_name, manufacturer_id, category_id) values ('nullasm sit', 33, 8);
insert into products (product_name, manufacturer_id, category_id) values ('at velit', 95, 7);
insert into products (product_name, manufacturer_id, category_id) values ('lecstus', 6, 1);
insert into products (product_name, manufacturer_id, category_id) values ('nunc purus', 52, 9);
insert into products (product_name, manufacturer_id, category_id) values ('neque', 90, 2);
insert into products (product_name, manufacturer_id, category_id) values ('luctus', 84, 1);
insert into products (product_name, manufacturer_id, category_id) values ('praessent', 5, 10);
insert into products (product_name, manufacturer_id, category_id) values ('quiss tortor', 96, 2);
insert into products (product_name, manufacturer_id, category_id) values ('sesm mauris', 62, 1);
insert into products (product_name, manufacturer_id, category_id) values ('voslutpat', 46, 10);
insert into products (product_name, manufacturer_id, category_id) values ('laoreet', 76, 1);
insert into products (product_name, manufacturer_id, category_id) values ('nullam sit', 80, 5);
insert into products (product_name, manufacturer_id, category_id) values ('diasm', 14, 9);
insert into products (product_name, manufacturer_id, category_id) values ('amxet', 19, 5);
insert into products (product_name, manufacturer_id, category_id) values ('blandit lacinia', 91, 4);
insert into products (product_name, manufacturer_id, category_id) values ('diams', 33, 9);
insert into products (product_name, manufacturer_id, category_id) values ('etiam pretium', 65, 6);
insert into products (product_name, manufacturer_id, category_id) values ('nam dui', 25, 2);
insert into products (product_name, manufacturer_id, category_id) values ('sed', 71, 10);
insert into products (product_name, manufacturer_id, category_id) values ('sits', 6, 2);
insert into products (product_name, manufacturer_id, category_id) values ('nuldla', 8, 3);
insert into products (product_name, manufacturer_id, category_id) values ('diaasm', 74, 8);

