insert into profiles (user_id, birthday, hometown, gender) values (1, '21.1.1990', 'Jasieniec', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (2, '14.4.1973', 'Trnovska Vas', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (3, '9.8.1982', 'Metz', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (4, '20.11.1982', 'Zlatoust', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (5, '9.6.1979', 'Qijiaxi', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (6, '8.5.2016', 'Huasahuasi', 'M');
insert into profiles (user_id, birthday, hometown, gender) values (7, '8.11.1998', 'Nueva Requena', 'M');
insert into profiles (user_id, birthday, hometown, gender) values (8, '17.7.2010', 'Cabrero', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (9, '12.7.1973', 'Alilem', 'M');
insert into profiles (user_id, birthday, hometown, gender) values (10, '13.2.1983', 'Sumbermanggis', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (11, '10.4.1979', 'Luocun', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (12, '17.9.2009', 'Kutno', 'M');
insert into profiles (user_id, birthday, hometown, gender) values (13, '20.8.1997', 'Huangchen', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (14, '22.6.2023', 'Canjulao', 'M');
insert into profiles (user_id, birthday, hometown, gender) values (15, '7.1.2005', 'Mucllo', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (16, '15.1.2003', 'Castedo', 'M');
insert into profiles (user_id, birthday, hometown, gender) values (17, '30.9.2011', 'Jayaraga Kaler', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (18, '11.9.1973', 'Bangilan', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (19, '15.10.2000', 'Bjelovar', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (20, '6.4.1980', 'Basseterre', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (21, '13.9.1976', 'Yoshkar-Ola', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (22, '3.6.2016', 'Onueke', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (23, '14.3.2009', 'Wentang', 'M');
insert into profiles (user_id, birthday, hometown, gender) values (24, '13.3.1992', 'Berezovo', 'M');
insert into profiles (user_id, birthday, hometown, gender) values (25, '6.4.1971', 'Jami', 'M');
insert into profiles (user_id, birthday, hometown, gender) values (26, '10.12.1997', 'Gujun', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (27, '17.2.1974', 'Aleksandrovac', 'M');
insert into profiles (user_id, birthday, hometown, gender) values (28, '17.2.1983', 'Bodø', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (29, '20.12.1980', 'Notre Dame', 'F');
insert into profiles (user_id, birthday, hometown, gender) values (30, '12.8.2016', 'Cofimvaba', 'F');

select * from profiles;
