insert into towns (town_name) values ('Reshetnikovo');
insert into towns (town_name) values ('Zarumilla');
insert into towns (town_name) values ('Campo Mourão');
insert into towns (town_name) values ('Kari');
insert into towns (town_name) values ('Sobinka');
insert into towns (town_name) values ('Baluk');
insert into towns (town_name) values ('Villa Carlos Paz');
insert into towns (town_name) values ('Shenji');
insert into towns (town_name) values ('Sukabumi');
insert into towns (town_name) values ('Lebedinovka');
insert into towns (town_name) values ('Martin');
insert into towns (town_name) values ('Perfilovo');
insert into towns (town_name) values ('Kuala Belait');
insert into towns (town_name) values ('Wukang');
insert into towns (town_name) values ('Imaan');
insert into towns (town_name) values ('Saint Joseph');
insert into towns (town_name) values ('Josefův Důl');
insert into towns (town_name) values ('San Buenaventura');
insert into towns (town_name) values ('Nynäshamn');
insert into towns (town_name) values ('Āzādshahr');
insert into towns (town_name) values ('Amga');
insert into towns (town_name) values ('Mungyeong');
insert into towns (town_name) values ('Bahía Blanca');
insert into towns (town_name) values ('Culasian');
insert into towns (town_name) values ('Gurinai');
insert into towns (town_name) values ('Mocun');
insert into towns (town_name) values ('Duyanggang');
insert into towns (town_name) values ('�?Eilabun');
insert into towns (town_name) values ('Darwin');
insert into towns (town_name) values ('Pankovka');
insert into towns (town_name) values ('Njurunda');
insert into towns (town_name) values ('Novaya Lyalya');
insert into towns (town_name) values ('Moscow');
insert into towns (town_name) values ('Metsavan');
insert into towns (town_name) values ('Wuluo');
insert into towns (town_name) values ('Kota Trieng');
insert into towns (town_name) values ('Chicago');
insert into towns (town_name) values ('Dar Chabanne');
insert into towns (town_name) values ('Manadhoo');
insert into towns (town_name) values ('Ust-Kamenogorsk');
insert into towns (town_name) values ('Jintian');
insert into towns (town_name) values ('Muroto-misakicho');
insert into towns (town_name) values ('Skála Oropoú');
insert into towns (town_name) values ('Kristinehamn');
insert into towns (town_name) values ('Wang Sam Mo');
insert into towns (town_name) values ('Mikuni');
insert into towns (town_name) values ('Kroczyce');
insert into towns (town_name) values ('Qarqania');
insert into towns (town_name) values ('Longbei');
insert into towns (town_name) values ('Kalengwa');
insert into towns (town_name) values ('Chechenglu');
insert into towns (town_name) values ('Cileueur');
insert into towns (town_name) values ('Tanggungrejo');
insert into towns (town_name) values ('Jinxiang');
insert into towns (town_name) values ('Storuman');
insert into towns (town_name) values ('Lichinga');
insert into towns (town_name) values ('Daswr Chabanne');
insert into towns (town_name) values ('Huangbao');
insert into towns (town_name) values ('Casais Baleal');
insert into towns (town_name) values ('Izazi');
insert into towns (town_name) values ('Thị Trấn Việt Quang');
insert into towns (town_name) values ('Valjevo');
insert into towns (town_name) values ('Meicheng');
insert into towns (town_name) values ('Żabno');
insert into towns (town_name) values ('Nuyno');
insert into towns (town_name) values ('Xintian');
insert into towns (town_name) values ('Greenhills');
insert into towns (town_name) values ('Tebara');
insert into towns (town_name) values ('Puerto Santander');
insert into towns (town_name) values ('Mutsu');
insert into towns (town_name) values ('Tongzhong');
insert into towns (town_name) values ('Mojoroto');
insert into towns (town_name) values ('Zernograd');
insert into towns (town_name) values ('Pekijing');
insert into towns (town_name) values ('Mkushi');
insert into towns (town_name) values ('Tambakbaya');
insert into towns (town_name) values ('Koynare');
insert into towns (town_name) values ('Zhuyeping');
insert into towns (town_name) values ('Sirnaresmi');
insert into towns (town_name) values ('Svyetlahorsk');
insert into towns (town_name) values ('Pangao');
insert into towns (town_name) values ('Finspång');
insert into towns (town_name) values ('Sundsvall');
insert into towns (town_name) values ('Hengshi');
insert into towns (town_name) values ('Mboto');
insert into towns (town_name) values ('Luan Balu');
insert into towns (town_name) values ('Bayt Ta�?mar');
insert into towns (town_name) values ('Xitan');
insert into towns (town_name) values ('Pragen Selatan');
insert into towns (town_name) values ('Seso');
insert into towns (town_name) values ('Potrerillos');
insert into towns (town_name) values ('Rungkam');
insert into towns (town_name) values ('Seixo da Beira');
insert into towns (town_name) values ('Makilala');
insert into towns (town_name) values ('Kimhae');
insert into towns (town_name) values ('Invercargill');
insert into towns (town_name) values ('Shigu');
insert into towns (town_name) values ('Cikiwul Satu');
insert into towns (town_name) values ('Oslo');
insert into towns (town_name) values ('Popovo');
